### ISSUE TITLE
Authorize webhook to call wc-api

### ISSUE THREAD

**Issue by f4nu** [satispay/woocommerce-plugin#1]
Hi, I'm getting some webhook calls from Satispay (I'm now in the staging phase) and we're obviously denying them as they come from unknown sources.

Is there an IP list or some sort of authorization code in the headers to know if the call is not a hoax?

**Comment by stvnmsh** [comment]
Hi, you can follow this [configurations](https://developers.satispay.com/reference#firewall-configuration).
