### ISSUE TITLE
Missing file from new wordpress version

### ISSUE THREAD

**Issue by sidelux** [satispay/woocommerce-plugin#17]
Hello,

from the 2.2.0 update i get Wordpress on error on two of my websistes:
_PHP Warning:  require_once(includes/blocks/wc-satispay-blocks.php): failed to open stream: No such file or directory in /var/www/html/xxx/wp-content/plugins/woo-satispay/woo-satispay.php on line 40_

This is the actual plugin directory:
<img width="189" alt="image" src="https://github.com/satispay/woocommerce-plugin/assets/18572941/88bd9119-2395-484b-a890-5d8483ddccdd">

I checked and it really miss the file, also after a clean reinstall.
Probably is an error during plugin update upload on Wordpress marketplace.

How i can i fix? Thanks a lot!

**Comment by red-made** [comment]
Start by downloading the zip from this repo and overwrite the plugin

**Comment by sidelux** [comment]
Now it works, thanks.
