### ISSUE TITLE
Use wordpress configuration to bypass Corporate Firewall 

### ISSUE THREAD

**Issue by r4770** [satispay/woocommerce-plugin#3]
Hi,

We are using this plugin in our wordpress-woocommerce instance inside a corporate network under a firewall. 
The exit proxy has been configured in wp-config.php which allows wordpress to go out on the internet (which allows access to remote resources transparently). 

How can I configure the proxy on this plugin or let use of the wordpress proxy configuration?

wp-config.php (proxy config)
```
define('WP_PROXY_HOST', 'proxy-host');
define('WP_PROXY_PORT', '8080');
define('WP_PROXY_USERNAME', '');
define('WP_PROXY_PASSWORD', '');
define('WP_PROXY_BYPASS_HOSTS', 'localhost, 10.*');
```

Best Regards
RAFFAELE

**Comment by r4770** [comment]
Hi!

thanks for implementing the proxy options of wp-config.php! 

I tried the changes and they work fine. 
I hope the merge request is approved soon!

@stiven-satispay @mirkocesaro @adnsio

**Comment by keeara** [comment]
solved
