### ISSUE TITLE
missing is_enabled check, description and order number/customer details on business dashboard

### ISSUE THREAD

**Issue by andreDane** [satispay/woocommerce-plugin#5]
Hi,
we are trying to configure the plugin but there some things to fix before we could, so I ask you an help.

- [x]  payment gateway appears even if it is not enabled in woocommerce settings, so it could help to add  a statement like `if ( is_enabled() ) { ... }`;
![immagine](https://user-images.githubusercontent.com/80747609/125601140-139ae892-57a4-4eee-b082-e2bcf97c4453.png)

- [x] the method_description (addressed to shop manager and visible on the back-end) is the same of the description (addressed to customers and visible on the front-end), while I would expect them to be different depending on the target audience;
![immagine](https://user-images.githubusercontent.com/80747609/125601671-a07c90dc-78b2-4933-896b-d0889b0dabe7.png)
For instance, it could be easily done adding a 'description' field [here](https://github.com/satispay/woocommerce-plugin/blob/1bbdec8cbd8254b0c422e78186f4374bafbeafea/wc-satispay.php#L52) (to give shop manager the possibility to change the text) and then removing `$this->description = $this->method_description` from [here](https://github.com/satispay/woocommerce-plugin/blob/1bbdec8cbd8254b0c422e78186f4374bafbeafea/wc-satispay.php#L21) and finally adding `$this->description = $this->get_option( 'description' )` [here](https://github.com/satispay/woocommerce-plugin/blob/1bbdec8cbd8254b0c422e78186f4374bafbeafea/wc-satispay.php#L26);

- [x] it would be very useful to have the possibility to pass the sequential order number (instead of the order_id) and the name of customers (or email or id) in the Satispay Business Dashboard, in order to make easier the link between payments and orders; for instance, [here](https://github.com/satispay/woocommerce-plugin/blob/master/wc-satispay.php#L198) you could do `$order->get_order_number()` instead of `$order->get_id()`, because the first one is way more significant, and then maybe add:
`'customer_id'            => $order->get_customer_id(),`
`'customer_full_name' => $order->get_billing_first_name() . ' ' . $order->get_billing_last_name(),`
`'customer_email'       => $order->get_billing_email()`
![immagine](https://user-images.githubusercontent.com/80747609/125605682-9e4ea1ea-44d4-419d-9781-c3fa9d1d7c78.png)

Thank you in advance for your attention.
Kind regards.

**Comment by stvnmsh** [comment]
1. Fixed `is_available` function logic
2. Updated method description
3. Rejected
