### ISSUE TITLE
Missed redirect to thankyou page on mobile

### ISSUE THREAD

**Issue by dademaru** [satispay/woocommerce-plugin#8]
Hi,

when completing the order from **mobile** (e.g. Safari on iOS), you are directly switched to **Satispay App** (while on desktop you are redirected to Satispay site with QR-code and phone number input).

After paying, you are not automatically redirected on Safari.
You have to click the back link (OS default) on top left to switch back to Safari.

Then, in Safari, **you are not redirected to Thank-you page** (Order Completed page, e.g. `/checkout/order-received/{id}/?key=wc_order_{key}`), but you are still in checkout with the AJAX loading spinner.

This is a problem for the user, since he doesn't understand if the order has been successfully completed/processed or not and can't do anything to understand (by going back he's redirected to empty cart).

It's like the redirect action:
[`header('Location: '.$this->get_return_url($order));`](https://github.com/satispay/woocommerce-plugin/blob/master/wc-satispay.php#L163)
doesn't fire when completing purchases on mobile browser.

Could you please check?

Further details:
iOS 15.4
Safari 15.4
Satispay 3.19.0

Thanks

**Comment by stvnmsh** [comment]
Hi @dademaru, we are already working on a new version which support the web-app-web switch correctly.
